<?php

$cats = $this->getCategories();
?>
<div class="column">
    <div class="small-12 block block-featured">
        <div class="block-title">
            <h3>Featured Products</h3>

            <?php if (count($cats) > 0): ?>
                <ul class="featured-categories category menu" id="cat-menu">
                    <?php $c = 0;
                    foreach ($cats as $_category):
                        $c++; ?>
                        <li data-cat-id="<?php echo $_category->getId(); ?>"
                            class="<?php echo ($c == 1) ? 'active' : ''; ?>">
                            <span><?php echo $_category->getName() ?></span>
                        </li>
                    <?php endforeach; ?>

                </ul>

            <?php endif; ?>
        </div>
        <?php $c = 0;
        foreach ($cats as $_category):
            $c++;
            ?>
            <div
                class="block-content featured-grid category-<?php echo $_category->getId(); ?> <?php echo ($c == 1) ? 'active' : ''; ?>">
                <?php
                $collection = $this->getProductCollection($_category->getId());
                if ($count = count($collection) > 0):
                    ?>
                    <div class="products-grid products-grid--max-5-col" data-equalizer>
                        <?php
                        foreach ($collection as $_product) :
                            $producthelper = Mage::helper('catalog/output');
                            $_product = $product = $_product->load($_product->getId());
                            ?>
                            <div class="featured-item item">
                                <div class="wrapper">
                                    <a href="<?php echo $_product->getProductUrl() ?>" class="product-image"
                                       title="View <?php echo $_product->getName() ?> online">
                                        <img
                                                src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(250); ?>"
                                                alt="<?php echo $this->escapeHtml($_product->getName() . " ".$this->getImageLabel($_product, 'image')); ?>"
                                                title="<?php echo $this->escapeHtml($_product->getName() . " ".$this->getImageLabel($_product, 'image')); ?>" />
                                    </a>

                                    <div class="product-info">
                                        <h5 class="product-name">
                                            <a data-equalizer-watch href="<?php echo $_product->getProductUrl() ?>"
                                               title="View <?php echo $_product->getName() ?> online"><?php echo $_product->getName() ?></a>
                                        </h5>
                                        <?php
                                        echo $this->getPriceHtml($_product, true, '-featured');
                                        ?>
                                        <?php if ($_product->getRatingSummary()): ?>
                                            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                                        <?php endif; ?>
                                        <div class="actions">
                                            <?php if ($_product->isSaleable()): ?>
                                                <button type="button"
                                                        title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>"
                                                        class="button btn-cart"
                                                        onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                                                    <?php echo $this->__('Add to Cart') ?></button>
                                            <?php else: ?>
                                                <p class="availability out-of-stock">
                                                    <span><?php echo $this->__('Out of stock') ?></span></p>
                                            <?php endif; ?>
                                            <ul class="add-to-links">
                                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                                    <li>
                                                        <a href="<?php echo $this->getAddToWishlistUrl($_product) ?>"
                                                           class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a>
                                                    </li>
                                                <?php endif; ?>
                                                <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                                                    <li><span class="separator">|</span> <a
                                                            href="<?php echo $_compareUrl ?>"
                                                            class="link-compare"><?php echo $this->__('Add to Compare') ?></a>
                                                    </li>
                                                <?php endif; ?>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                <?php else : ?>
                    <p class="error">No Products in this collection</p>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    </div>
</div>
