<div class="small-12">
    <div class="page-title">
        <h2>New <?php echo ($this->getGender() == 'Male') ? 'Men' : 'Women'; ?> Products</h2>
        <div class="slider-arrows slider-arrows-<?php echo ($this->getGender() == 'Male') ? 'men' : 'women'; ?>">
            <span>Drag OR </span>
            <button type="button" title="previous set" class="prev fa  fa-chevron-left" aria-hidden="true"></button>
            <button type="button" title="next set" class="next fa  fa-chevron-right" aria-hidden="true"></button>
        </div>
     </div>
    <div class="slick-slider products-grid" id="<?php echo ($this->getGender() == 'Male') ? 'men-new' : 'women-new'; ?>" data-equalizer>
        <?php
        $collection = $this->getProductCollection($this->getGender());

        foreach ($collection as $_product) :

            $producthelper = Mage::helper('catalog/output');
            ?>
            <div class="item" data-equalizer-watch>
                <a href="<?php echo $_product->getProductUrl() ?>"
                   title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                   class="product-image">
                    <img
                        data-original="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(270); ?>"
                        alt="Buy <?php echo $this->stripTags($_product->getName(), null, true) ?> from fashion threads boutique"
                        class="lazy"/>
                    <noscript>
                        <img
                            src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(270); ?>"
                            alt="Buy <?php echo $this->stripTags($_product->getName(), null, true) ?> from fashion threads boutique"/>
                    </noscript>
                </a>

                <h4 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>"
                                            title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $producthelper->productAttribute($_product, $_product->getName(), 'name') ?></a>
                </h4>
                <?php if ($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; ?>
                <?php
                $productBlock = $this->getLayout()->createBlock('catalog/product_price');
                echo $productBlock->getPriceHtml($_product, true) ?>
                <div class="actions">
                    <?php if ($_product->isSaleable()): ?>
                        <button type="button"
                                title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>"
                                class="button btn-cart"
                                onclick="setLocation('<?php echo Mage::helper('checkout/cart')->getAddUrl($_product) ?>')">
                            <span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    <?php else: ?>
                        <p class="availability out-of-stock">
                            <span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"
                                   class="link-wishlist"></a></li>
                        <?php endif; ?>
                        <?php if ($_compareUrl = Mage::helper('catalog/product_compare')->getAddUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>"
                                                                    class="link-compare"></a></li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>

<script>
    jQuery(document).ready(function(){
        jQuery('.slick-slider').foundation('_reflow');

        jQuery('.slider-arrows-<?php echo ($this->getGender() == 'Male') ? 'men' : 'women'; ?> button.next').click(function() {
            jQuery("#<?php echo ($this->getGender() == 'Male') ? 'men-new' : 'women-new'; ?>").slick("slickNext");
        });
        jQuery('.slider-arrows-<?php echo ($this->getGender() == 'Male') ? 'men' : 'women'; ?> button.prev').click(function() {
            jQuery("#<?php echo ($this->getGender() == 'Male') ? 'men-new' : 'women-new'; ?>").slick("slickPrev");
        });
    })


</script>